import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../globals.css'
import { Toaster } from 'sonner'
import { ThemeProvider } from '@/shared/lib/theme-provider'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

import { ThemeToggle } from '@/shared/ui/theme-toggle'

export default function AuthLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					<div
						className='h-screen w-screen bg-cover bg-center bg-no-repeat flex items-center justify-center'
						style={{ backgroundImage: "url('/assets/auth-bg.png')" }}
					>
						<ThemeToggle />
						<div className='w-[630px] bg-card text-card-foreground border border-border rounded-[24px] px-10 py-20 text-center shadow-lg transition-colors'>
							{children}
						</div>
						<Toaster position='top-right' richColors closeButton />
					</div>
				</ThemeProvider>
			</body>
		</html>
	)
}
